// user
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTOLOGIN = 'AUTOLOGIN';
export const REGISTERATION = 'REGISTERATION';
export const SETUSERDATA = 'SETUSERDATA';
export const UPDATEUSERIMG = 'UPDATEUSERIMG';
export const LOGINLOADING = 'LOGINLOADING';
export const UPDATEUSERDATA = 'UPDATEUSERDATA';
export const UPDATEDEVICTOKEN = 'UPDATEDEVICTOKEN';

// Book
export const SETBOOKREAD = 'SETBOOKREAD';
export const UPDATEFAVBOOKS = 'UPDATEFAVBOOKS';
// Author
export const SETAUTHORS = 'SETAUTHORS';
export const UPDATEFAVAUTHORS = 'UPDATEFAVAUTHORS';

// Genre
export const SETGENRES = 'SETGENRES';
