require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Booky' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'Firebase/Analytics'

  pod 'Firebase/Messaging'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'


  target 'BookyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({'Flipper' => '0.58.0'})
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Booky-tvOS' do
  # Pods for Booky-tvOS

  target 'Booky-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end